main.o: main.c mb_api.h
mb_api.o: mb_api.c mb_api.h mb_cu.h mb_basic.h list.h mb_pu.h
mb_basic.o: mb_basic.c mb_basic.h list.h mb_api.h
mb_pu.o: mb_pu.c mb_pu.h mb_basic.h list.h mb_api.h
search_device.o: search_device.c mb_api.h \
 /home/shiyong/usr/include/nampu/search_device.h
mb_cu.o: mb_cu.c mb_cu.h mb_basic.h list.h mb_api.h
