# Makefile for nmp-mds

.PHONY: clean install uninstall

./bin/nmp-mss:
	test -z ./bin || mkdir -p ./bin
	make -C ./core

clean:
	make -C ./core cleanall

install:
	@echo "to be continued"

uninstall:
	@echo "to be continued"
