#include <signal.h>
#include "nmp_audit.h"
#include "nmp_debug.h"
#include "nmp_tq.h"
#include "nmp_sysctl.h"

#define AUDIT_FREQ 	5

typedef struct _JpfRateCounter JpfRateCounter;
struct _JpfRateCounter
{
	gulong total_size;		/* rate counter v1 */
	gulong last_total;
};

struct _JpfAuditContext
{
	JpfRateCounter rate_src;
	JpfRateCounter rate_sinker;

	gint media_srcs;
	gint media_sinkers;
	gint stream_srcs;
	gint stream_sinkers;
};

static JpfAuditContext nmp_audit_ctx;
static gint audit_off = 1;
static gint triggered = 0;
static gint request_rti = 0;
static FILE *rti_file = NULL;

static __inline__ void
nmp_audit_add_rate_bytes(JpfRateCounter *r, gulong size)
{
	r->total_size += size;
}


static __inline__ gulong
nmp_audit_get_rate(JpfRateCounter *r, gint time_slice)
{
	gulong delta;

	delta = r->total_size - r->last_total;
	r->last_total = r->total_size;
	return (delta << 3) / time_slice;
}


static __inline__ void
__nmp_audit_inc(JpfAuditContext *ctx, JpfAuditType type, gint v)
{
	switch (type)
	{
	case AUDIT_BRATE_SRC:
		nmp_audit_add_rate_bytes(&ctx->rate_src, v);
		break;

	case AUDIT_BRATE_SINKER:
		nmp_audit_add_rate_bytes(&ctx->rate_sinker, v);
		break;		

	case AUDIT_CNT_MEDIA_SRC:
		ctx->media_srcs += v;
		break;

	case AUDIT_CNT_MEDIA_SNK:
		ctx->media_sinkers += v;
		break;

	case AUDIT_CNT_STREAM_SRC:
		ctx->stream_srcs += v;
		break;

	case AUDIT_CNT_STREAM_SNK:
		ctx->stream_sinkers += v;
		break;

	default:
		break;
	}	
}


void
nmp_audit_inc(JpfAuditType type, gint v)
{
	__nmp_audit_inc(&nmp_audit_ctx, type, v);
}


void nmp_audit_dec(JpfAuditType type, gint v)
{
	__nmp_audit_inc(&nmp_audit_ctx, type, -v);	
}


void nmp_audit_zero(JpfAuditContext *ctx)
{
	memset(ctx, 0, sizeof(*ctx));
}


static __inline__ void
nmp_rti_file_open( void )
{
	gchar *rti_file_path;

	if (rti_file)
		return;

	rti_file_path = g_strdup_printf("%s/%s", 
		(gchar*)nmp_get_sysctl_value(SC_LOG_PATH),
		"Jpf-mds.inf");
	rti_file = fopen(rti_file_path, "w+");
	if (!rti_file)
	{
		nmp_warning(
			"Open rti file '%s' failed.", rti_file_path
		);
	}
	else
	{
		fprintf(rti_file, "# This file was automatically generated by MDS\n");
		fprintf(rti_file, "#     -- Run Time Information --\n\n");
	}

	g_free(rti_file_path);
}


static __inline__ void
nmp_rti_file_close( void )
{
	if (!rti_file)
		return;

	fclose(rti_file);
	rti_file = NULL;
}


static __inline__ void
nmp_rti_write_state(gint state)
{
	if (!rti_file)
		return;

	fprintf(rti_file, "state:%d\n", state);
}


static __inline__ void
nmp_rti_write_media_info(gint media_sinkers, gint stream_sinkers, gdouble o_rate,
	gint media_srcs, gint stream_srcs, gdouble i_rate)
{
	if (!rti_file)
		return;

	fprintf(rti_file, "m_out:%d\n", media_sinkers);
	fprintf(rti_file, "s_out:%d\n", stream_sinkers);
	fprintf(rti_file, "o_rate:%.2fMbps\n", o_rate);
	fprintf(rti_file, "m_in:%d\n", media_srcs);
	fprintf(rti_file, "s_in:%d\n", stream_srcs);
	fprintf(rti_file, "i_rate:%.2fMbps\n", i_rate);
}


static void
nmp_audit_output(void *parm)
{
	static guint freq;
	JpfAuditContext *ctx = (JpfAuditContext*)parm;
	gdouble i_rate, o_rate;
	gint rti_state;

	if (triggered)
	{
		triggered = 0;
		if (audit_off)
		{
			nmp_print("Audit Output Disabled");
		}
		else
		{
			nmp_print("Audit Output Enabled");
		}
	}

	if (!(++freq % AUDIT_FREQ))
	{
		i_rate = ((gdouble)nmp_audit_get_rate(&ctx->rate_src, AUDIT_FREQ)) / (1000 * 1000);
		o_rate = ((gdouble)nmp_audit_get_rate(&ctx->rate_sinker, AUDIT_FREQ)) / (1000 * 1000);

		if (!audit_off)
		{
			nmp_print(
				"=== [OUT] %d Meds, %d Stms, %.2f Mbps; [IN] %d Meds, %d Stms, %.2f Mbps ===",
				ctx->media_sinkers,
				ctx->stream_sinkers,
				o_rate,
				ctx->media_srcs,
				ctx->stream_srcs,
				i_rate
			);
		}
	}

	if (request_rti)
	{
		extern gint nmp_media_server_state( void );

		i_rate = ((gdouble)nmp_audit_get_rate(&ctx->rate_src, AUDIT_FREQ)) / (1000 * 1000);
		o_rate = ((gdouble)nmp_audit_get_rate(&ctx->rate_sinker, AUDIT_FREQ)) / (1000 * 1000);

		nmp_print("Dump RTI info.");
		rti_state = nmp_media_server_state();
		nmp_rti_file_open();
		nmp_rti_write_state(rti_state);
		nmp_rti_write_media_info(ctx->media_sinkers,
		                         ctx->stream_sinkers,
		                         o_rate,
		                         ctx->media_srcs,
		                         ctx->stream_srcs,
		                         i_rate);
		nmp_rti_file_close();
		request_rti = 0;
	}
}


static __inline__ void
__nmp_audit_init(JpfAuditContext *ctx)
{
	static JpfTq audit_tq;

	TQ_INIT(&audit_tq, nmp_audit_output, ctx);
	nmp_add_tq(&audit_tq);
}


static __inline__ void
nmp_audit_change_state( void )
{
	audit_off = !audit_off;
	triggered = 1;
}


static __inline__ void
nmp_request_rti_info( void )
{
	request_rti = 1;
}


static void
nmp_on_sig(int sig)
{
	switch (sig)
	{
	case SIGUSR1:
		nmp_audit_change_state();
		break;

	case SIGUSR2:
		nmp_request_rti_info();
		break;

	default:
		break;
	}
}


void nmp_audit_init( void )
{
	static volatile gsize g_init_audit = 0;
	if (g_once_init_enter(&g_init_audit))
	{
		__nmp_audit_init(&nmp_audit_ctx);
		signal(SIGUSR1, nmp_on_sig);
		signal(SIGUSR2, nmp_on_sig);
		g_once_init_leave(&g_init_audit, 1);
	}
}

//:~ End
