# Makefile.def for nmp-cms

C++	= g++
CC 	= gcc
AR 	= ar
LD	= ld

C_SRCS		= ${shell find . -name "*.c"}
C_OBJS		= ${patsubst %.c, %.o, ${C_SRCS}}

CPP_SRCS	= ${shell find . -name "*.cpp"}
CPP_OBJS	= ${patsubst %.cpp, %.o, ${CPP_SRCS}}

PRJ_CFLAGS	= -Wall -g -fno-inline -fstack-protector
PRJ_CPPFLAGS 	= -Wall -g -fno-inline -fstack-protector

GLIB_VERSION	:= 2.0
GLIB_LIBS	:= glib-${GLIB_VERSION} gobject-${GLIB_VERSION} gthread-${GLIB_VERSION}

PRJ_INCLUDES	+= -I${shell pkg-config --cflags ${GLIB_LIBS}}
PRJ_INCLUDES	+= -I${HOME}/usr/include/nampu

PRJ_LIBS	+= ${shell pkg-config --libs ${GLIB_LIBS}}
PRJ_LIBS	+= -Wl,-rpath=${HOME}/usr/lib -L${HOME}/usr/lib -lnmpshare -lnmpframework

vpath %h ${HOME}/usr/include/nampu
