.PHONY: nmp_cms clean install uninstall

nmp-cms:
	test -z ./bin || mkdir -p ./bin
	make -C ./src/core

clean:
	make -C ./src/core cleanall

install:
	@echo "to be continued"

uninstall:
	@echo "to be continued"
