# Makefile for proxy-server

.PHONY: all clean install uninstall

all:
	make -C ./bin

clean:
	make -C ./bin clean
	make -C ./mod clean
	make -C ./utils clean
	make -C ./core clean

install:
	@echo "Sorry, install command will be enable in the future.\n"

uninstall:
	@echo "Sorry, install command will be enable in the future.\n"
