#! /bin/sh

#**********************************************************
#* set-release-env
#*
#* This script create compile environment of release version.
#*
#* Copyright(c) by HiMickey, 2010~2014
#* Author: HiMickey
#* Date: Jan 11th, 2011
#*
#**********************************************************

if [ $SHARE_PRX ]
then
	export CFLAGS="$CFLAGS -O2"
	export CXXFLAGS="$CXXFLAGS -O2"
	export TAR_DIR=$SHARE_PRX/release
else
	echo "ERROR: Current share prefix is NULL!"
	echo ""
	echo "Please source the environment script at first!"
	echo "usually: source ${HOME}/pd-libs/env/[environment script]"
	echo ""
fi



