#include "rti.h"
#include "nmp_debug.h"
#include "nmp_sysctl.h"
#include "nmp_tq.h"

static gint rti_request = 0;
static FILE *rti_file = NULL;

static __inline__ void
nmp_rti_file_open( void )
{
	gchar *rti_file_path;

	if (rti_file)
		return;

	rti_file_path = g_strdup_printf("%s/%s", 
		(gchar*)nmp_get_sysctl_value(SC_LOG_PATH),
		"Nmp-mss.inf");
	rti_file = fopen(rti_file_path, "w+");
	if (!rti_file)
	{
		nmp_warning(
			"Open rti file '%s' failed.", rti_file_path
		);
	}
	else
	{
		fprintf(rti_file, "# This file was automatically generated by MSS\n");
		fprintf(rti_file, "#     -- Run Time Information --\n\n");
	}

	g_free(rti_file_path);
}


static __inline__ void
nmp_rti_file_close( void )
{
	if (!rti_file)
		return;

	fclose(rti_file);
	rti_file = NULL;
}


static __inline__ void
nmp_rti_write_state(gint state)
{
	if (!rti_file)
		return;

	fprintf(rti_file, "state:%d\n", state);
}


static void
nmp_rti_output(void *parm)
{
	gint state;

	if (rti_request)
	{
		extern gint nmp_mod_cms_state( void );
		state = nmp_mod_cms_state();
		nmp_rti_file_open();
		nmp_rti_write_state(state);
		nmp_rti_file_close();
		rti_request = 0;
	}
}


static void
nmp_on_sig(int sig)
{
	rti_request = 1;
}


void nmp_rti_init( void )
{
	static NmpTq rti_tq;

	TQ_INIT(&rti_tq, nmp_rti_output, NULL);
	nmp_add_tq(&rti_tq);
	signal(SIGUSR2, nmp_on_sig);
}

//:~ End
