# Makefile.def for h264pack

C++	= g++
CC 	= gcc
AR 	= ar
LD	= ld

C_SRCS		= ${shell find . -name "*.c"}
C_OBJS		= ${patsubst %.c, %.o, ${C_SRCS}}

CPP_SRCS	= ${shell find . -name "*.cpp"}
CPP_OBJS	= ${patsubst %.cpp, %.o, ${CPP_SRCS}}

PRJ_CFLAGS	= -Wall -g -fno-inline -fstack-protector -fPIC -m32
PRJ_CPPFLAGS 	= -Wall -g -fno-inline -fstack-protector -fPIC -m32

PRJ_DEFINE	= -D_X86_
PRJ_INCLUDES	:=

PRJ_LIBS	+= -Wl,-rpath=${NMP_LIB_INSTALL}/lib -L${NMP_LIB_INSTALL}/lib -lpthread -lrt
PRJ_LDFLASG	+= -fPIC
