.PHONY: talksvr clean install uninstall

talksvr:
	make -C ./core
	make -C ./test

clean:
	make -C ./core clean
	make -C ./test clean

install:
	@echo "to be continued"

uninstall:
	@echo "to be continued"
