#ifndef _COMMANDERROR_H_
#define _COMMANDERROR_H_

#include "GeneralError.h"

//-401 => -500

#define SN_ERROR_COMMAND_BEGIN					(-400)

//未知命令
#define SN_ERROR_COMMAND_UNKNOW					(SN_ERROR_COMMAND_BEGIN - 1)

//命令头解析错误
#define SN_ERROR_COMMAND_HEAD_PARSE_ERROR		(SN_ERROR_COMMAND_BEGIN - 2)

//命令头创建错误
#define SN_ERROR_COMMAND_HEAD_CREATE_ERROR		(SN_ERROR_COMMAND_BEGIN - 3)

//命令负载解析错误
#define SN_ERROR_COMMAND_PAYLOAD_PARSE_ERROR	(SN_ERROR_COMMAND_BEGIN - 4)

//命令负载创建错误
#define SN_ERROR_COMMAND_PAYLOAD_CREATE_ERROR	(SN_ERROR_COMMAND_BEGIN - 5)

//命令版本错误
#define SN_ERROR_COMMAND_VERSION_ERROR			(SN_ERROR_COMMAND_BEGIN - 6)




#endif // 
