#ifndef _NETWORKIOERROR_H_
#define _NETWORKIOERROR_H_
#include "GeneralError.h"

//-201 => -300

#define SN_ERROR_DETWORKIO_BEGIN				(-200)

//网络SOCKET没有创建
#define SN_ERROR_NETWORKIO_NOTCREATE			(SN_ERROR_DETWORKIO_BEGIN - 1)

//网络SOCKET创建失败
#define SN_ERROR_NETWORKIO_CREATE_FAILED		(SN_ERROR_DETWORKIO_BEGIN - 2)

//网络SOCKET绑定失败
#define SN_ERROR_NETWORKIO_BIND_FAILED			(SN_ERROR_DETWORKIO_BEGIN - 3)

//网络SOCKET链接失败
#define SN_ERROR_NETWORKIO_CONNECT_FAILED		(SN_ERROR_DETWORKIO_BEGIN - 4)

//网络SOCKET链接超时
#define SN_ERROR_NETWORKIO_CONNECT_TIMEOUT		(SN_ERROR_DETWORKIO_BEGIN - 5)

//网络SOCKET侦听失败
#define SN_ERROR_NETWORKIO_LISTEN_FAILED		(SN_ERROR_DETWORKIO_BEGIN - 6)

//TCP接受网络SOCKET失败
#define SN_ERROR_NETWORKIO_ACCEPT_FAILED		(SN_ERROR_DETWORKIO_BEGIN - 7)

//TCP接受网络SOCKET超时
#define SN_ERROR_NETWORKIO_ACCEPT_TIMEOUT		(SN_ERROR_DETWORKIO_BEGIN - 8)

//网络SOCKET链接中断
#define SN_ERROR_NETWORKIO_DISCONNECT			(SN_ERROR_DETWORKIO_BEGIN - 9)

//网络SOCKET发送失败
#define SN_ERROR_NETWORKIO_SEND_FAILED			(SN_ERROR_DETWORKIO_BEGIN - 10)

//网络SOCKET发送超时
#define SN_ERROR_NETWORKIO_SEND_TIMEOUT			(SN_ERROR_DETWORKIO_BEGIN - 11)

//网络SOCKET接收失败
#define SN_ERROR_NETWORKIO_RECEIVE_FAILED		(SN_ERROR_DETWORKIO_BEGIN - 12)

//网络SOCKET接收超时
#define SN_ERROR_NETWORKIO_RECEIVE_TIMEOUT		(SN_ERROR_DETWORKIO_BEGIN - 13)

//获取SOCKET地址失败
#define SN_ERROR_NETWORKIO_GETSOCKADDR_FAILED	(SN_ERROR_DETWORKIO_BEGIN - 14)

//设置网络SOCKET选项配置失败
#define SN_ERROR_NETWORKIO_SETOPTION_FAILED		(SN_ERROR_DETWORKIO_BEGIN - 15)

//获取网络SOCKET选项配置失败
#define SN_ERROR_NETWORKIO_GETOPTION_FAILED		(SN_ERROR_DETWORKIO_BEGIN - 16)

//不支持的协议
#define SN_ERROR_NETWORKIO_PROTOCOL_NOT_SUPPORT	(SN_ERROR_DETWORKIO_BEGIN - 17)

//端口已经被占用
#define SN_ERROR_NETWORKIO_PORT_USED			(SN_ERROR_DETWORKIO_BEGIN - 18)
//////////////////////////////////////////////////////
//创建包失败
#define SN_ERROR_PACKET_CREATE_FAILED			(SN_ERROR_DETWORKIO_BEGIN - 30)

//包头解析错误
#define SN_ERROR_PACKET_HEAD_PARSE_ERROR		(SN_ERROR_DETWORKIO_BEGIN - 31)

//包头创建错误
#define SN_ERROR_PACKET_HEAD_CREATE_ERROR		(SN_ERROR_DETWORKIO_BEGIN - 32)

//包体解析错误
#define SN_ERROR_PACKET_PAYLOAD_PARSE_ERROR		(SN_ERROR_DETWORKIO_BEGIN - 33)

//包体创建错误
#define SN_ERROR_PACKET_PAYLOAD_CREATE_ERROR	(SN_ERROR_DETWORKIO_BEGIN - 34)

//RTP
//RTP扩展头解析错误
#define SN_ERROR_RTP_EXTENDHEAD_PARSE_ERROR		(SN_ERROR_DETWORKIO_BEGIN - 35)

//通信压缩失败
#define SN_ERROR_PACKET_COMPRESS_ERROR			(SN_ERROR_DETWORKIO_BEGIN - 36)

//域名解析错误
#define SN_ERROR_DOMAIN_NAME_PARSE_ERROR		(SN_ERROR_DETWORKIO_BEGIN - 37)

//非阻塞sokcet发送重试请求
#define SN_ERROR_NETWORKIO_SOCKET_AGAIN			(SN_ERROR_DETWORKIO_BEGIN - 38)

#endif // 
