# Makefile for nmp-mds

.PHONY: clean install uninstall

./src/nmp-mds:
	test -z ./bin || mkdir -p ./bin
	make -C ./src

clean:
	make -C ./src cleanall

install:
	@echo "to be continued"

uninstall:
	@echo "to be continued"
